[build]
  command = "npm ci --force && npm run build"
  publish = "out"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  PYTHON = "/usr/bin/python3"
  npm_config_python = "/usr/bin/python3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[context.deploy-preview]
  skip = true